# ~/.config/starship.toml

# Use custom format

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 500

# Disable the blank line at the start of the prompt
add_newline = false


#format = "$all"
# Use custom format
# After new line, the topics appear before the input shell
format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$package\
$terraform\
$gcloud\
$aws\
$nix_shell\
$env_var\
$kubernetes\
$cmd_duration\
$line_break\
$jobs\
$battery\
$memory_usage\
$time\
$character\
"""

# Replace the "â¯" symbol in the prompt with "âœ"
[character]      # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"
vicmd_symbol = "[âœ](bold green)"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "

[[battery.display]]
threshold = 30
style = "bold red"

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
threshold = 70
style = "bold dimmed white"
disabled = false

[kubernetes]
disabled = false
#symbol = "â˜¸ "

[directory]
truncation_length = 3
truncation_symbol = "â€¦/"
format = "[$path]($style)[$read_only]($read_only_style) "
read_only = "ğŸ”’"
read_only_style = "red"

# shows the hostname on new lines
[hostname]
ssh_only = false
disabled = false
style = "bold italic #87A752"

[docker_context]
format = "via [ğŸ‹ $context](blue bold)"
detect_files = ["docker-compose.yml", "docker-compose.yaml", "Dockerfile"]

[git_branch]
#symbol = "ğŸŒ± "
truncation_length = 25
truncation_symbol = "â€¦/"

[helm]
format = "via [âˆ $version](bold white) "

[terraform]
format = "[ $symbol$version-$workspace]($style) "
symbol = "ğŸ’ "
detect_extensions = ["tf", "hcl"]

[gcloud]
format = '[$symbol($project)]($style) '
#format = 'on [$symbol$account(\($project\))]($style) '
style = "bold blue"

[aws]
format = 'on [$symbol($profile )(\($region\) )]($style)'
symbol = "â˜"
style = "bold yellow"
disabled = true

[time]
format = "at [$time]($style) "
style = "bold purple"
disabled = true


